#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute
api_login_check_cook:
  path: /api/cooks/auth/login

api_login_check_order:
  path: /api/orders/auth/login