twig:
    default_path: '%kernel.project_dir%/src/Common/Infrastructure/Twig/templates'
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/src/Meal/Infrastructure/Twig/Mail/Templates': 'meal'

when@test:
    twig:
        strict_variables: true
